before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle/"

stages:
- build
- deploy
- release
- docs

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/
    expire_in: 10 days
  cache:
    paths:
      - .gradle/

maven_publish:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  image: eclipse-temurin:21-jdk-noble
  script:
    - ./gradlew publish
  cache:
    paths:
      - .gradle/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Extracting changelog entry for $CI_COMMIT_TAG"
    - echo -e "# Changelog\n" > CHANGELOG_ENTRY.md
    - awk -v tag="$CI_COMMIT_TAG" '/^## *\[.+\]/ { i=index($0,tag); l=length(tag); if (i>0 && substr($0,i+l,1)=="]") keep=1; else keep=0; } keep' CHANGELOG.md >> CHANGELOG_ENTRY.md
  release:
    tag_name: $CI_COMMIT_TAG
    name: UhcCore $CI_COMMIT_TAG
    description: ./CHANGELOG_ENTRY.md
    assets:
      links:
        - name: uhccore-$CI_COMMIT_TAG.jar
          url: https://gitlab.com/api/v4/groups/uhccore/-/packages/maven/net/zerodind/uhccore/$CI_COMMIT_TAG/uhccore-$CI_COMMIT_TAG.jar
          filepath: /plugin-jar
          link_type: package

pages:
  image: python:3.10-bullseye
  stage: docs
  before_script:
    - apt-get update
    - apt-get install brotli
  script:
    - cd docs
    - python -m pip install -r requirements.txt
    - mkdocs build -d ../public
    - cd ..
    - find public -type f -regex '.*\.\(htm\|html\|js\|css\|txt\|json\|svg\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|js\|css\|txt\|json\|svg\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - docs/**/*
        - .gitlab-ci.yml
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
